// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class AnalysisBiomaterial : IAnalysisBiomaterial
{
    public int AnalysisBiomaterialId { get; set; }

    public int AnalysisId { get; set; }

    public int BiomaterialId { get; set; }

    public virtual Analysis Analysis { get; set; }

    public virtual Biomaterial Biomaterial { get; set; }

    IAnalysis IAnalysisBiomaterial.Analysis
    {
        get => Analysis;
        set => Analysis = (Analysis)value;
    }

    IBiomaterial IAnalysisBiomaterial.Biomaterial
    {
        get => Biomaterial;
        set => Biomaterial = (Biomaterial)value;
    }
}