// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class AnalysisCategory : IAnalysisCategory
{
    public int AnalysisCategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Analysis> Analyses { get; set; } = new List<Analysis>();

    ICollection<IAnalysis> IAnalysisCategory.Analyses
    {
        get => Analyses.Cast<IAnalysis>().ToList();
        set => Analyses = value.Cast<Analysis>().ToList();
    }
}