// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class AnalysisResult : IAnalysisResult
{
    public int AnalysisResultId { get; set; }

    public int OrderAnalysisId { get; set; }

    public int Indicator { get; set; }

    public DateTime ExecutionDate { get; set; }

    public string Description { get; set; }

    public virtual OrderAnalysis OrderAnalysis { get; set; }
}