// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class Biomaterial : IBiomaterial
{
    public int BiomaterialId { get; set; }

    public string BiomaterialName { get; set; }

    public virtual ICollection<AnalysisBiomaterial> AnalysisBiomaterials { get; set; } = new List<AnalysisBiomaterial>();
}