// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class Laboratory : ILaboratory
{
    public int LaboratoryId { get; set; }

    public string Address { get; set; }

    public int CityId { get; set; }

    public string PhoneNumber { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<LaboratorySchedule> LaboratorySchedules { get; set; } = new List<LaboratorySchedule>();
}