// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class LaboratorySchedule : ILaboratorySchedule
{
    public int LaboratoryScheduleId { get; set; }

    public int LaboratoryId { get; set; }

    public int ScheduleId { get; set; }

    public virtual Laboratory Laboratory { get; set; }

    public virtual Schedule Schedule { get; set; }
}