// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class OrderAnalysis : IOrderAnalysis
{
    public int OrderAnalysisId { get; set; }

    public int AnalysisId { get; set; }

    public int OrderId { get; set; }

    public virtual Analysis Analysis { get; set; }

    public virtual ICollection<AnalysisResult> AnalysisResults { get; set; } = new List<AnalysisResult>();

    public virtual Order Order { get; set; }
}