// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class Order : IOrder
{
    public int OrderId { get; set; }

    public int? Number { get; set; }

    public int StatusId { get; set; }

    public int EmployeeId { get; set; }

    public int ClientId { get; set; }

    public DateTime BiomaterialCollectionDate { get; set; }

    public double Fullprice { get; set; }

    public virtual Client Client { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<OrderAnalysis> OrderAnalyses { get; set; } = new List<OrderAnalysis>();

    public virtual Status Status { get; set; }

    ICollection<IOrderAnalysis> IOrder.OrderAnalyses
    {
        get => OrderAnalyses.Cast<IOrderAnalysis>().ToList();
        set => OrderAnalyses = value.Cast<OrderAnalysis>().ToList();
    }

    IClient IOrder.Client
    {
        get => Client;
        set => Client = (Client)value;
    }

    IEmployee IOrder.Employee
    {
        get => Employee;
        set => Employee = (Employee)value;
    }

    IStatus IOrder.Status
    {
        get => Status;
        set => Status = (Status)value;
    }
}