// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class Position : IPosition
{
    public int PositionId { get; set; }

    public string PositionName { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    ICollection<IEmployee> IPosition.Employees
    {
        get => Employees.Cast<IEmployee>().ToList();
        set => Employees = value.Cast<Employee>().ToList();
    }
}