// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LabA.Abstraction.IModel;

namespace LabA.DAL.Models;

public partial class Sex : ISex
{
    public int SexId { get; set; }

    public string SexName { get; set; }

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();
}